# Generated by Django 3.0.5 on 2020-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('c_name', models.CharField(max_length=15)),
                ('c_quantity', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
                ('address', models.TextField(default='abcde')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='#####', max_length=10)),
                ('item_name', models.CharField(max_length=20)),
                ('item_quamntity', models.CharField(max_length=20)),
                ('perishable', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('typ', models.CharField(max_length=8)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
                ('address', models.TextField(default='abcde')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='#####', max_length=10)),
                ('house_location', models.TextField()),
                ('size', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('rent', models.IntegerField(max_length=4)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
                ('address', models.TextField(default='abcde')),
            ],
        ),
        migrations.CreateModel(
            name='Other_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=25)),
                ('item_quantity', models.CharField(max_length=20)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
                ('address', models.TextField(default='abcde')),
            ],
        ),
        migrations.CreateModel(
            name='PPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('kiit_name', models.CharField(max_length=25)),
                ('kiit_quantity', models.CharField(max_length=20)),
                ('ph_no', models.CharField(default='0000000000', max_length=10)),
                ('address', models.TextField(default='abcde')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('u_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank='True', max_length=10, unique='True')),
                ('address', models.TextField()),
            ],
        ),
    ]
