# Generated by Django 3.0.5 on 2020-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank='True', max_length=10),
        ),
    ]
