# Generated by Django 3.0.5 on 2020-06-12 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_auto_20200612_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
