# Generated by Django 3.0.5 on 2020-06-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20200612_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='home',
            name='date',
        ),
        migrations.RemoveField(
            model_name='other_item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ppe',
            name='date',
        ),
    ]
