# Generated by Django 3.0.5 on 2020-07-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_auto_20200701_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
