# Generated by Django 3.0.5 on 2020-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0007_auto_20200701_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
