# Generated by Django 3.0.5 on 2020-07-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0008_auto_20200701_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Profile'),
        ),
        migrations.AlterField(
            model_name='food',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Profile'),
        ),
        migrations.AlterField(
            model_name='home',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Profile'),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Profile'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Profile'),
        ),
    ]
