# Generated by Django 3.0.5 on 2020-07-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0009_auto_20200701_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
