# Generated by Django 3.0.5 on 2020-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0010_auto_20200702_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='c_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='c_quantity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_quamntity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='size',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='item_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='item_quantity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='kiit_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='kiit_quantity',
            field=models.TextField(),
        ),
    ]
