# Generated by Django 3.0.5 on 2020-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0011_auto_20200713_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent',
            field=models.TextField(),
        ),
    ]
