# Generated by Django 3.0.5 on 2020-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0012_auto_20200713_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent',
            field=models.IntegerField(),
        ),
    ]
