# Generated by Django 3.0.5 on 2020-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0013_auto_20200724_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='status',
            field=models.TextField(default='aaaa'),
        ),
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.TextField(default='aaaa'),
        ),
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.TextField(default='aaaa'),
        ),
        migrations.AddField(
            model_name='other_item',
            name='status',
            field=models.TextField(default='aaaa'),
        ),
        migrations.AddField(
            model_name='ppe',
            name='status',
            field=models.TextField(default='aaaa'),
        ),
    ]
