# Generated by Django 3.0.5 on 2020-08-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0014_auto_20200802_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='status',
            field=models.TextField(default='Available'),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.TextField(default='Available'),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.TextField(default='Available'),
        ),
        migrations.AlterField(
            model_name='other_item',
            name='status',
            field=models.TextField(default='Available'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='status',
            field=models.TextField(default='Available'),
        ),
    ]
