# Generated by Django 3.0.5 on 2020-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0016_auto_20200802_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
