# Generated by Django 3.0.5 on 2020-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0019_auto_20200802_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
